package com.univalle.bubackend.models;

public enum OdontologyReason {
    AYUDAS_DIAGNOSTICAS,
    FORMULACION_DE_MEDICAMENTOS,
    HIGIENE_ORAL,
    REMISION_A_OTRAS_DEPENDENCIAS,
    RESINA_DE_FOTOCURADO,
    REVALORACION,
    URGENCIA_ODONTOLOGICA,
    VALORACION_PRIMERA_VEZ
}
